google_analytics_id: G-GSRQ6JMLTZ
theme: jekyll-theme-slate
url: https://kuroshiro.org
baseurl: ""
include:
  - assets/vendor
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - scripts
  - test
  - WEBSITE.md
  - gemfile
